### ISSUE TITLE
webrick dependency exception with jekyll serve attempt: ruby 3.0 + macOS 

### ISSUE THREAD

**Issue by chrissimpkins** [unified-font-object/ufo-spec#156]
macOS 10.15.7
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

I used the README documentation to install documentation build dependencies and attempt to serve the files with jekyll using the command `bundle exec jekyll serve`.  I received the following error:

```
Configuration file: /Users/chris/code-ext/ufo-spec/_config.yml
            Source: /Users/chris/code-ext/ufo-spec
       Destination: /Users/chris/code-ext/ufo-spec/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.429 seconds.
 Auto-regeneration: enabled for '/Users/chris/code-ext/ufo-spec'
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:179:in `require_relative'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:179:in `setup'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:100:in `process'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /usr/local/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/jekyll:23:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/cli.rb:497:in `exec'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
```

This is a [known issue with Jekyll + Ruby 3](https://github.com/jekyll/jekyll/issues/8523) because webrick is no longer bundled with Ruby 3. 

It was addressed with the recommendation in https://github.com/jekyll/jekyll/issues/8523#issuecomment-751409319 which added the following line to my Gemfile:

```
gem "webrick", "~> 1.7"
```

I can serve the local HTML files without issues using that change.

I don't have much experience with Ruby and gem dependency management, but I think that the only change necessary here is that a user should be instructed to use `bundle add webrick` if they are using Ruby 3.0+.

**Comment by benkiel** [comment]
@chrissimpkins I updated the gem file, does that look good to you? If so, I'll merge

**Comment by chrissimpkins** [comment]
Thanks Ben!

I can confirm that `bundle exec jekyll serve` works with the changes at https://github.com/unified-font-object/ufo-spec/pull/157/commits/057cf40093387c0f305c322cb2650e363781c8b3 in the same environment listed in the OP.

I don't know how that approach will work for Ruby < 3.0 where webrick is bundled with the ruby distribution.

**Comment by chrissimpkins** [comment]
https://github.com/jekyll/jekyll/issues/8523#issuecomment-761074500

**Comment by benkiel** [comment]
@chrissimpkins I don't have experience there either, nor do I have a great test environment for that. I'll do some searching and see what I find, then either merge or not. Thanks for asking that over at jekyll, will follow
